NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from news.views import subscriptions

urlpatterns = [
    path('', RedirectView.as_view(url='/posts/')),  # Redirect root URL to /news/
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    #path("accounts/", include("accounts.urls")),  # Добавили эту строчку
    path("accounts/", include("allauth.urls")),  # Оставили только allauth
    path('pages/', include('django.contrib.flatpages.urls')),
    path('posts/', include('news.urls')),  # Include news URLs
    path('subscriptions/', subscriptions, name='subscriptions'),
    # Other URL patterns
]

NewsPaper/news/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import (PostsList, PostDetail, search_news,
                    EditPostView,
                    CreateNewsView, CreateArticleView, DeletePostView
                    )
from django.views.decorators.cache import cache_page # импортируем декоратор для кэширования отдельного представления



urlpatterns = [

    # path — означает путь.
    # В данном случае путь ко всем post у нас останется пустым,
    # чуть позже станет ясно почему.
    # Т.к. наше объявленное представление является классом,
    # а Django ожидает функцию, нам надо представить этот класс в виде view.
    # Для этого вызываем метод as_view.
    path('', PostsList.as_view(), name='post_list'),
    # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
    # int — указывает на то, что принимаются только целочисленные значения
    path('<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('search/', search_news, name='search_news'),
    #path('news/create/', cache_page(60*5)(CreateNewsView.as_view()), name='create_news'),
    #path('news/<int:pk>/edit/', cache_page(60*5)(EditPostView.as_view()), name='edit_news'),
    #path('news/<int:pk>/delete/', cache_page(60*5)(DeletePostView.as_view()), name='delete_news'),
    #path('articles/create/', cache_page(60*5)(CreateArticleView.as_view()), name='create_article'),
    #path('articles/<int:pk>/edit/', cache_page(60*5)(EditPostView.as_view()), name='edit_article'),
    #path('articles/<int:pk>/delete/', cache_page(60*5)(DeletePostView.as_view()), name='delete_article'),

    path('news/create/', CreateNewsView.as_view(), name='create_news'),
    path('news/<int:pk>/edit/', EditPostView.as_view(), name='edit_news'),
    path('news/<int:pk>/delete/', DeletePostView.as_view(), name='delete_news'),
    path('articles/create/', CreateArticleView.as_view(), name='create_article'),
    path('articles/<int:pk>/edit/', EditPostView.as_view(), name='edit_article'),
    path('articles/<int:pk>/delete/', DeletePostView.as_view(), name='delete_article'),

]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
from django.core.cache import cache

from django.core.mail import send_mail

class Author(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        # Суммарный рейтинг каждой статьи автора умножается на 3
        post_rating = sum(post.rating for post in self.post_set.all()) * 3

        # Суммарный рейтинг всех комментариев автора
        comment_rating = sum(comment.rating for comment in Comment.objects.filter(post__author=self))

        # Суммарный рейтинг всех комментариев к статьям автора
        post_comment_rating = sum(comment.rating for comment in Comment.objects.filter(post__author=self))

        # Обновляем рейтинг автора
        self.rating = post_rating + comment_rating + post_comment_rating
        self.save()

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    ARTICLE = 'article'
    NEWS = 'news'
    POST_CHOICES = [
        (ARTICLE, 'Article'),
        (NEWS, 'News'),
    ]


    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        preview_length = 124
        if len(self.text) <= preview_length:
            return self.text
        else:
            return self.text[:preview_length].strip() + '...'

    #To save news/articles in create I added settings.AUTH_USER_MODEL here:
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    #author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    post_type = models.CharField(max_length=7, choices=POST_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=200)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')  # Удаляем объект из кэша при его сохранении

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.pk)])

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

class Comment(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscriptions')
    subscribed_categories = models.ManyToManyField(Category, related_name='subscriptions')

    def __str__(self):
        return self.email

NewsPaper/templates/create_article.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Create article</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/create_news.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Create news</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/delete_article.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Delete article</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure to delete "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/delete_news.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Delete news</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure to delete "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/edit_article.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Edit article</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/edit_news.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Edit news</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/post.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}
{% load custom_filters %}!
{% block title %}
    {% if post %}
        {{ post.title }}
    {% else %}
        Post
    {% endif %}
{% endblock title %}

{% block content %}
    {% if post %}
        <h1>{{ post.title }}</h1>
        <p>Publication date: {{ post.created_at|date:"d.m.Y" }}</p>
        <p>{{ post.text|censor }}</p>
    {% else %}
        <h1>Post</h1>
    {% endif %}
{% endblock content %}

NewsPaper/templates/posts.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}!
{% load custom_tags %}

{% block title %}
Posts
{% endblock %}

{% block content %}
<!-- Вывод количества новостей -->
<h1>Today's posts</h1>
    <p>Number of news: {{ Posts|length }}</p>
    <ul>
        {% for post in page_obj %}
            <li>
                <h2>{{ post.title }}</h2>
                <p>Publication date: {{ post.created_at|date:"d.m.Y l" }}</p>
                <p>{{ post.text|truncatewords:30|censor }}</p>
                {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                 <!-- Гиперссылка для изменения новости/статьи -->
                {% if perms.news.change_post %}
                    <a href="{% url 'edit_news' pk=post.pk %}">Edit</a>
                {% endif %}
                {% if perms.news.delete_post %}
                    <a href="{% url 'delete_news' pk=post.pk %}">Delete</a>
                {% endif %}


            </li>
        {% endfor %}
    </ul>


 {# Добавляем пагинацию на страницу #}

 {# Pagination #}
<div class="pagination">
    {% if is_paginated %}
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    {% else %}
        <p>No results found.</p>
    {% endif %}
</div>
{% endblock %}

NewsPaper/templates/search_news.html
<!-- наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
    Search post
{% endblock %}
{% block content %}
    <h1>Search Posts</h1>
<!-- Search Form -->
<form method="GET" action="{% url 'search_news' %}">
        <input type="text" name="q" placeholder="Search news by title" value="{{ request.GET.q }}">
        <select name="category">
            <option value="">All Categories</option>
            <!-- Populate the dropdown menu with available categories -->
            {% for category in categories %}
                <option value="{{ category.name }}" {% if request.GET.category == category.name %} selected {% endif %}>{{ category.name }}</option>
            {% endfor %}
        </select>
        <input type="date" name="date" placeholder="Search news by date" value="{{ request.GET.date }}">
        <button type="submit">Search</button>
    </form>
    {% if search_results %}
        <h2>Search Results</h2>
        <ul>
            {% for post in search_results %}
                <li>
                    <h3>{{ post.title|censor }}</h3>
                    <p>{{ post.text|censor }}</p>
                    <p>Category:
                            {% for category in post.categories.all %}
                                {{ category.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                    </p>
                    <p>Date: {{ post.created_at }}</p>
                </li>
            {% endfor %}
        </ul>
<!-- Pagination links -->
    <div class="pagination">
        <span class="step-links">
            {% if search_results.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ search_results.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ search_results.number }} of {{ search_results.paginator.num_pages }}.
            </span>

            {% if search_results.has_next %}
                <a href="?page={{ search_results.next_page_number }}">next</a>
                <a href="?page={{ search_results.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% else %}
    <p>No results found.</p>
    {% endif %}

{% endblock %}

NewsPaper/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
<!--{% load cache %}-->
<!--{% cache 300 category_list %}-->
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
<!--{% endcache %}-->
{% endblock content %}